package com.seanshubin.inversion.guard.workflow

object ConfigDocumentation {
    val documentationDescription = listOf(
        "Brief description of what this tool does",
        "Inversion guard analyzes dependencies between classes to detect architectural violations",
        "Helps AI assistants and developers understand the purpose of the application"
    )
    val documentationReadme = listOf(
        "Link to the README file for detailed documentation",
        "Should be a URL to the project's README on GitHub or similar"
    )
    val documentationConfigHelp = listOf(
        "Name of the JSON file containing detailed help for each configuration setting",
        "This file is automatically generated with documentation for all config keys"
    )
    val inputDir = listOf(
        "The directory from which to start scanning for class files",
        "All class files under this directory will be analyzed for dependencies"
    )
    val outputDir = listOf(
        "The directory where the analysis report will be generated",
        "HTML and JSON reports will be written to this location"
    )
    val classesIncludeFile = listOf(
        "List of regular expression patterns for class files to include in analysis",
        "Files must match at least one include pattern to be analyzed",
        "Example: \".*/target/.*\\\\.class\" to include all .class files in target directories"
    )
    val classesExcludeFile = listOf(
        "List of regular expression patterns for class files to exclude from analysis",
        "Files matching any exclude pattern will be skipped even if they match an include pattern"
    )
    val classesSkipDir = listOf(
        "List of directory name patterns to skip during file scanning",
        "Directories matching these patterns will not be traversed"
    )
    val globalRules = listOf(
        "Path to the JSON file containing global category and boundary rules",
        "This file defines the architectural categories (core/boundary) for the project",
        "Example: inversion-guard-rules.json"
    )
    val localRulesCore = listOf(
        "List of package patterns to classify as 'core' in addition to global rules",
        "Core classes should not depend on boundary classes",
        "Local rules are combined with global rules from the globalRules file"
    )
    val localRulesBoundary = listOf(
        "List of package patterns to classify as 'boundary' in addition to global rules",
        "Boundary classes handle external interactions (I/O, network, databases)",
        "Local rules are combined with global rules from the globalRules file"
    )
    val failOnUnknown = listOf(
        "Whether to fail the build if classes are found that don't match any category",
        "When true, all classes must be categorized as either core or boundary",
        "When false, uncategorized classes are reported but don't cause build failure"
    )
    val maximumAllowedErrorCount = listOf(
        "Maximum number of architectural violations allowed before build fails",
        "Set to 0 to enforce zero violations",
        "Useful for gradually improving existing codebases"
    )
}
